### ISSUE TITLE
Docker: GLIBC_2.38 not found

### ISSUE THREAD

**Issue by fumbles** [MVS-sysgen/sysgen#61]
Interesting find when running the docker container.

We're using 2.35 in the image it looks like

```

[*] Starting Hercules
hercules: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.38' not found (required by /home/hercules/herctest/herc4x/lib/libherc.so)
hercules: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.38' not found (required by /home/hercules/herctest/herc4x/lib/libhercu.so)
hercules: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.38' not found (required by /home/hercules/herctest/herc4x/lib/libhercd.so)
```

```
docker run --rm -it --entrypoint="/bin/bash" mainframed767/mvsce:latest 

root@ab065e7f5f69:/# ldd --version
ldd (Ubuntu GLIBC 2.35-0ubuntu3.9) 2.35
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

my docker-compose file: 
```
services:
  mvsce:
    image: mainframed767/mvsce:latest
    container_name: mvsce
    ports:
      - "3271:3270"
      - "2121:21"
      - "2323:23"
      - "3505:3505"
      - "3506:3506"
      - "8892:8888"
    stdin_open: true     # Optional: for interactive console
    tty: true            # Optional: for interactive terminal
    environment:
      HUSER: docker
      HPASS: docker
    volumes:
      - ./mvsce_data/dasd:/dasd
      - ./mvsce_data/log:/logs
      - ./mvsce_data/printers:/printers
      - ./mvsce_data/punchcards:/punchcards
      - ./mvsce_data/certs:/certs
      - ./mvsce_data:/config
    restart: unless-stopped
```
